package com.example.dmain.gymfit.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dmain.gymfit.database.Data;
import com.example.dmain.gymfit.database.Exercises;
import com.example.dmain.gymfit.database.Series;

import com.example.dmain.gymfit.database.DataDao;
import com.example.dmain.gymfit.database.ExercisesDao;
import com.example.dmain.gymfit.database.SeriesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig exercisesDaoConfig;
    private final DaoConfig seriesDaoConfig;

    private final DataDao dataDao;
    private final ExercisesDao exercisesDao;
    private final SeriesDao seriesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        exercisesDaoConfig = daoConfigMap.get(ExercisesDao.class).clone();
        exercisesDaoConfig.initIdentityScope(type);

        seriesDaoConfig = daoConfigMap.get(SeriesDao.class).clone();
        seriesDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        exercisesDao = new ExercisesDao(exercisesDaoConfig, this);
        seriesDao = new SeriesDao(seriesDaoConfig, this);

        registerDao(Data.class, dataDao);
        registerDao(Exercises.class, exercisesDao);
        registerDao(Series.class, seriesDao);
    }
    
    public void clear() {
        dataDaoConfig.clearIdentityScope();
        exercisesDaoConfig.clearIdentityScope();
        seriesDaoConfig.clearIdentityScope();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public ExercisesDao getExercisesDao() {
        return exercisesDao;
    }

    public SeriesDao getSeriesDao() {
        return seriesDao;
    }

}
